apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy100
  labels:
    app: autodeploy100
  namespace: namespace-workflow-1710143512455
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy100
  template:
    metadata:
      labels:
        app: autodeploy100
    spec:
      containers:
        - name: autodeploy100
          image: acrworkflow1710143512455.azurecr.io/image-workflow-1710143512455:latest
          ports:
            - containerPort: 5000